package edu.ics240.dispatch.core;

/**
 * Advisory validation outcomes for Step 6.
 */
public enum ValidationStatus {
    RECOMMENDATION_EXPIRED,
    CALL_NO_LONGER_REQUIRED,
    SUPERSEDE_AND_REBUILD,
    
    SELECTION_VALID, CALL_NO_LONGER_REQUIRES_DISPATCH, OK, CALL_NOT_FOUND, NO_WAITING_CALL, NO_ELIGIBLE_AMBULANCE, DISPATCH_REJECTED, NO_AMBULANCE_SELECTED, AMBULANCE_UNAVAILABLE, AMBULANCE_NOT_FOUND
}
